model_path: outputs/z46wbgoe.ckpt
max_seq_len: 128
do_translation: True
do_reconstruction: True
do_ppl: True
data:
  dataset_name: wmt14
  language_pair: de-en
  batch_size: 4
  max_batches: 16
  num_workers: 8
  split: validation
generation:
  num_beams: 4
  max_new_tokens: 64
  do_sample: False