hydra:
  run:
    dir: ${oc.env:SCRATCH,.}/outputs/supervised/${now:%Y-%m-%d}/${now:%H-%M-%S}

data:
  dataset_name: wmt14
  language_pair: en-de
  stream: False
  train_split: train
  val_split: validation
  num_workers: 8

training:
  batch_size: 64
  gradient_accumulation: 1
  max_seq_len: 256
  learning_rate: 0.0001
  max_steps: 100000
  max_epochs: 50
  num_beams: 4
  val:
    check_interval: 512
    limit_batches: 512
    bleu_eval_freq: 2048
