hydra:
  run:
    dir: ${oc.env:SCRATCH,.}/outputs/unsupervised/${now:%Y-%m-%d}/${now:%H-%M-%S}
data:
  dataset_name: wmt14
  language_pair: de-en
  stream: False
  train_split: train
  val_split: validation
  num_workers: 8
model:
  use_oracle: True
  latent_regularizer: lnorm
  num_encoder_layers: 4
  num_decoder_layers: 6
  vq:
    n_codes: 1024
    n_groups: 8
training:
  batch_size: 16
  accumulate_batches: 1
  learning_rate: 0.0001
  max_steps: 100000
  max_epochs: 50
  max_seq_len: 128
  val:
    check_interval: 256
    limit_batches: 128
